import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import org.apache.commons.io.FilenameUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alial
 */
public class MainGUI extends JFrame {
    
    
    /**
     * Creates new form NewJFrame
     */
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moveFileChooser = new javax.swing.JFileChooser();
        VisibleFilesTitle = new java.awt.Label();
        ImageHolderPanel = new java.awt.Panel();
        MainImage = new javax.swing.JLabel();
        MainDirectorySearch = new javax.swing.JFileChooser();
        MainFileListScroll = new javax.swing.JScrollPane();
        MainFileList = new javax.swing.JTree();
        fileName = new javax.swing.JTextField();
        ApplyButton = new javax.swing.JButton();
        BaskScroll = new javax.swing.JScrollPane();
        Basket = new javax.swing.JTree();
        BasketLabel = new java.awt.Label();
        MoveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        videoSlider = new javax.swing.JSlider();
        pausePlayButton = new javax.swing.JButton();

        moveFileChooser.setCurrentDirectory(new java.io.File("D:\\"));
            moveFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setMaximumSize(new java.awt.Dimension(644, 399));
            setMinimumSize(new java.awt.Dimension(644, 399));
            setPreferredSize(new java.awt.Dimension(644, 399));

            VisibleFilesTitle.setAlignment(java.awt.Label.CENTER);
            VisibleFilesTitle.setFont(new java.awt.Font("Dialog", 0, 32)); // NOI18N
            VisibleFilesTitle.setText("Visible Files");

            ImageHolderPanel.setBackground(new java.awt.Color(0, 0, 0));
            ImageHolderPanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
            ImageHolderPanel.setPreferredSize(new java.awt.Dimension(590, 520));

            MainImage.setBackground(new java.awt.Color(0, 0, 0));
            MainImage.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
            MainImage.setPreferredSize(new java.awt.Dimension(1040, 768));

            javax.swing.GroupLayout ImageHolderPanelLayout = new javax.swing.GroupLayout(ImageHolderPanel);
            ImageHolderPanel.setLayout(ImageHolderPanelLayout);
            ImageHolderPanelLayout.setHorizontalGroup(
                ImageHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 590, Short.MAX_VALUE)
                .addGroup(ImageHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainImage, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            ImageHolderPanelLayout.setVerticalGroup(
                ImageHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 520, Short.MAX_VALUE)
                .addGroup(ImageHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainImage, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            MainDirectorySearch.setApproveButtonText("Select Folder");
            MainDirectorySearch.setCurrentDirectory(new java.io.File("D:\\Downloads"));
            MainDirectorySearch.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
            MainDirectorySearch.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    MainDirectorySearchActionPerformed(evt);
                }
            });

            MainFileListScroll.setMinimumSize(new java.awt.Dimension(0, 0));
            MainFileListScroll.setPreferredSize(new java.awt.Dimension(1526, 998));

            javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Files");
            MainFileList.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
            MainFileList.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
                public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                    MainFileListValueChanged(evt);
                }
            });
            MainFileListScroll.setViewportView(MainFileList);

            fileName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

            ApplyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            ApplyButton.setText("Apply");
            ApplyButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ApplyButtonActionPerformed(evt);
                }
            });

            treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Files");
            Basket.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
            BaskScroll.setViewportView(Basket);

            BasketLabel.setFont(new java.awt.Font("Dialog", 0, 32)); // NOI18N
            BasketLabel.setPreferredSize(new java.awt.Dimension(169, 46));
            BasketLabel.setText("Basket");

            MoveButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            MoveButton.setText("Move");
            MoveButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    MoveButtonActionPerformed(evt);
                }
            });

            jLabel1.setText("00:00:00");
            jLabel1.setAlignmentY(0.0F);

            videoSlider.setMaximum(0);
            videoSlider.setPaintLabels(true);
            videoSlider.setToolTipText("");
            videoSlider.setValue(0);

            pausePlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download-icon-play+icon-1320183326084518754_16.png"))); // NOI18N
            pausePlayButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pausePlayButtonActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(MainFileListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MainDirectorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BasketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BaskScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(VisibleFilesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(pausePlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(videoSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ImageHolderPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ApplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(MoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ImageHolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MainDirectorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BasketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BaskScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ApplyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(MoveButton)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pausePlayButton)
                                        .addComponent(videoSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(140, 140, 140))))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(VisibleFilesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(MainFileListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents
    
    
    ImageHandling imageHandler = new ImageHandling();
    public static final ArrayList<String> videoTypeList = new ArrayList<>(Arrays.asList("webm","mkv","flv","flv","vob","ogv","ogg","drc","gif","gifv","mng","avi","MTS","M2TS","TS","mov","qt","wmv","yuv","rm","rmvb","viv","asf","amv","mp4","m4p","m4v","mpg","mp2","mpeg","mpe","mpv","mpg","mpeg","m2v","m4v","svi","3gp","3g2","mxf","roq","nsv", "flv","f4v","f4p","f4a","f4b"));
    public static final ArrayList<String> imageTypeList = new ArrayList<>(Arrays.asList("jpg","jpeg","jpe","jif","jfif","jfi","png","gif","webp","tiff","tif","raw","arw","cr2","nrw","psd","k25","bmp","dib","heif","heic","indd","ind","indt","jp2","j2k","jpf","jpx","jpm","mj2","svg","svgz","ai","eps"));
    public static final ArrayList<String> zipTypeList = new ArrayList<>(Arrays.asList("7z","arj","deb","pkg","rar","rpm","gz","z","zip"));
    public static File currentDirectory;
    
    
    public MainGUI() {
	

	setSize(new Dimension(1920,1080));
	
	initComponents();
	setLayout(new BorderLayout());
	
	MainFileList.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
	
	ImageHandling.play();
	
	
	videoSlider.setEnabled(false);
	setExtendedState(JFrame.MAXIMIZED_BOTH);
	
    }
    
    
    private void MainDirectorySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainDirectorySearchActionPerformed
	
	
	MainListManager listManagerClass = new MainListManager();
	
	
	
	MainImage.setIcon(null);
	fileName.setText(null);
	
	try {
	    listManagerClass.addItemsToMainList(MainFileList, evt);
	} catch (IOException ex) {
	    Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
	}
	MainFileList.clearSelection();
	MainFileList.repaint();
	
    }//GEN-LAST:event_MainDirectorySearchActionPerformed

    private void MainFileListValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_MainFileListValueChanged
        
	
	
	//System.out.println(MainListManager.fileMapList.size());
	fileName.setText(getFileNameWithoutExtension(evt.getPath()));
	imageHandler.handler(treePathCombiner(evt.getPath(),0), MainImage);
	
	
	
	
	
	
    }//GEN-LAST:event_MainFileListValueChanged
    
    
    private void ApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyButtonActionPerformed

	if(!"null".equals(MainFileList.getSelectionPath().toString())){
	    //System.out.println(fileName.getText());
	    File originalFile = new File(treePathCombiner(MainFileList.getSelectionPath(),0));
	    
	    TreePath oldPath = MainFileList.getSelectionPath();
	    String newFileName = treePathCombiner(MainFileList.getSelectionPath(),1)+"\\"+fileName.getText()+"."+FilenameUtils.getExtension(originalFile.toString());
	    File renamedFile = new File(newFileName);
	    
	    
	    
	    
	    boolean flag = originalFile.renameTo(renamedFile);
	    if (flag == true) {
		DefaultTreeModel model = (DefaultTreeModel)MainFileList.getModel();
		DefaultMutableTreeNode childNode = (DefaultMutableTreeNode)MainFileList.getSelectionPath().getPath()[MainFileList.getSelectionPath().getPath().length-1];
		childNode.setUserObject(fileName.getText()+"."+FilenameUtils.getExtension(originalFile.toString()));
		model.nodeChanged(childNode);
		MainFileList.setModel(model);
		MainFileList.setSelectionPath(oldPath);
	    }else{
		System.out.println("exists");
	    }
	    
	    
	    
	    
	    
	}
	
    }//GEN-LAST:event_ApplyButtonActionPerformed

    private void MoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveButtonActionPerformed
        
	if (moveFileChooser.showDialog(this, "Select") == JFileChooser.APPROVE_OPTION){
	    if(MainFileList.getLastSelectedPathComponent()!=null){
		DefaultMutableTreeNode selectedFile = (DefaultMutableTreeNode) MainFileList.getLastSelectedPathComponent();
		FileClass selectedFileClass = (FileClass) selectedFile.getUserObject();
		if(!(new File(moveFileChooser.getSelectedFile().getAbsolutePath()+"\\"+MainFileList.getLastSelectedPathComponent()).isFile()) && (new File(selectedFileClass.absPath)).isFile()){
		    System.out.println("here");

		    try {
			selectedFileClass.moveFile(moveFileChooser.getSelectedFile().getAbsolutePath());
		    } catch (IOException ex) {
			Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
		    }
		}else if(!(new File(moveFileChooser.getSelectedFile().getAbsolutePath()+"\\"+MainFileList.getLastSelectedPathComponent()).isDirectory())){
		    System.out.println("true");
		    try {
			selectedFileClass.moveFolder(moveFileChooser.getSelectedFile().getAbsolutePath());
		    } catch (IOException ex) {
			Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
		    }
		}
	    }
	    
	    
	    
	    System.out.println(moveFileChooser.getSelectedFile());
	}
	
    }//GEN-LAST:event_MoveButtonActionPerformed

    private void pausePlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausePlayButtonActionPerformed
        if(ImageHandling.mediaExists()>0){
	    ImageHandling.pausePlay();
	    if(ImageHandling.isPlaying()){
		pausePlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download-icon-play+icon-1320183326084518754_16.png")));
	    }else{
		pausePlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download-icon-pause+icon-1320196062769593213_16.png")));
	    }
	}
	
	
    }//GEN-LAST:event_pausePlayButtonActionPerformed

    
    private String treePathCombiner(TreePath treePath, int endIndexRemover){
	StringBuilder finalPath = new StringBuilder();
	finalPath.append(currentDirectory);
	//System.out.println(treePath);
	for(int pathIndex = 1; pathIndex<treePath.getPathCount()-endIndexRemover; pathIndex++){
	    if(treePath.getPathComponent(pathIndex).toString().contains(":\\")){
		finalPath.deleteCharAt(finalPath.length()-1);
	    }else{
		finalPath.append("\\");
		finalPath.append(treePath.getPathComponent(pathIndex).toString());
	    }
	}	
	return finalPath.toString();
    }
    
    private String getFileNameWithoutExtension(TreePath treePath){
	String filename=treePath.getPathComponent(treePath.getPathCount()-1).toString();
	filename = filename.replaceAll("."+FilenameUtils.getExtension(filename), "");
	return filename;
    }
    
    private String findRelativeFilePos(Object[] pathIntArray){
	StringBuilder path = new StringBuilder();
	DefaultMutableTreeNode rootHead = (DefaultMutableTreeNode)MainFileList.getModel().getRoot();
	for (Object pathInt : pathIntArray) {
	    path.append("\\").append(rootHead.getChildAt((int)pathInt));
	    rootHead=(DefaultMutableTreeNode)rootHead.getChildAt((int)pathInt);
	    
	}
	return path.toString();
    }
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
	
        java.awt.EventQueue.invokeLater(new Runnable(){
	    public void run(){
		MainGUI mainGUI = new MainGUI();
		mainGUI.pack();
		
		mainGUI.setVisible(true);
	    }
	});
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyButton;
    private javax.swing.JScrollPane BaskScroll;
    public static javax.swing.JTree Basket;
    private java.awt.Label BasketLabel;
    public static java.awt.Panel ImageHolderPanel;
    public static javax.swing.JFileChooser MainDirectorySearch;
    public static javax.swing.JTree MainFileList;
    private static javax.swing.JScrollPane MainFileListScroll;
    public static javax.swing.JLabel MainImage;
    private javax.swing.JButton MoveButton;
    private java.awt.Label VisibleFilesTitle;
    private javax.swing.JTextField fileName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFileChooser moveFileChooser;
    public static javax.swing.JButton pausePlayButton;
    public static javax.swing.JSlider videoSlider;
    // End of variables declaration//GEN-END:variables
    
}
